
name: Infra Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - .github/workflows/deployDev.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/deployDev.yml

jobs:
  infra_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ARM-Templates/container-webapp-template.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}