
name: Infra Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - .github/workflows/deployDev.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/deployDev.yml

jobs:
  infra_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: "Hello"
      run: |
        echo "Hello Pipline"