
name: Infra Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - .github/workflows/deployDev.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/deployDev.yml

jobs:
  infra_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ARM-Templates/container-webapp-template.json
    
    # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
    
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
              body: body
            });
