name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - Application/**
      - .github/workflows/dotnet.yml
  pull_request:
    branches: [ master ]
    paths:
      - Application/**
      - .github/workflows/dotnet.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Application/src/RazorPagesTestSample
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore *.csproj
    - name: Build
      run: dotnet build --no-restore *.csproj
    - name: Test
      run: dotnet test --verbosity normal ../../tests/RazorPagesTestSample.Tests
